### ISSUE TITLE
Evaluation_PG :  A place-based approach to two-mode relational data

### ISSUE THREAD

**Issue by pgourdongeo** [rzine-reviews/place-rzine#2]
### Remarques d'ensemble

**Commentaire général** : Article bienvenu et très intéressant car, de manière générale, il existe peu de traitements et d’analyses des réseaux bi-modaux sur R qui ne soient pas sur le schéma _double-projection puis analyse uni-modale_. 

Dans la suite de l'évaluation, je fais de nombreux commentaires et suggestions mais qui vont dans le sens de coupes et de précisions et pas de réécritures trop lourdes. 

Cela dit : j'ai un gros point d'incertitude quant à ma propre compréhension de la méthode et je pense qu'il y aurait des choses à améliorer au début pour permettre au lecteur/à la lectrice de mieux cerner cette méthode et ses spécificités. 

**Une remarque sur le titre** : le vocable « _place-based approach_ » me semble vraiment trompeur pour les anglophones (et ce, malgré la note de précision dans le texte). En regardant la littérature sur l’équivalence structurale, les termes généraux les plus utilisées sont _roles_ et _position_ ( exemple :  [positional-analysis-in-networks](https://bookdown.org/markhoff/social_network_analysis/positional-analysis-in-networks.html ) ). Il me semble qu’une possibilité serait de garder _**place/places**_ comme dans le Pizarro (2007) avec une tournure qui souligne le statut de notion de _place_ : « Uncovering _places_ from two-mode networks : structural equivalence to study affiliation networks » ( ou un sous-titre plus précis en nommant le réseau étudié).

**Remarque générale sur la structure et la direction de l'article** : je rejoins Laurent  Beauguitte sur les parties 2 et 3 dans lesquelles on retrouve davantage un tutoriel sur les projections unimodales. Par conséquent, la spécificité de la méthode des places est, selon moi, moins mise en avant.
J’ai l’impression que la présentation de ce _package_ et de cette méthode pourrait prendre plusieurs directions (mais que l'article gagnerait à intensifier la direction 3) : 

1. Faire une comparaison de la méthode avec d’autres analyses : ici, par exemple, on pourrait comparer double projection classique (ou le block-modeling) à la méthode des places.
2. Faire une comparaison algorithmique/computationnelle : regarder les autres fonctions qui sont fondées sur l’équivalence structurale et comparer les sorties et les performances. Exemples :
- fonction [struc _equiv](https://search.r-project.org/CRAN/refmans/netdiffuseR/html/struct_equiv.html) {netdiffuseR} 
- [Structural et regular equivalence avec concoR](https://rstudio-pubs-static.s3.amazonaws.com/436072_01fce54f3c25458381fee52ec65396fc.html#structural_equivalence_methods)  
3. **Appliquer la méthode au cas d’étude et en montrer qualitativement/thématiquement l’intérêt** : il me semble que c’est cette option qui transparait à la lecture de l’article. Aussi une grande partie de mes remarques et suggestions ont pour objectif d’intensifier le texte dans ce sens, si l'autrice trouve cela pertinent. **Il me semble que l’on peut réduire significativement le nombre d’analyses et de calculs mais décrire davantage les résultats du point de vue thématique.**

### Un problème de compréhension (de ma part)

Je dois avouer que j'ai eu du mal avec les distinctions entre _place, set, element_. En première lecture tout me paraissait très clair mais en relisant, je me suis senti un peu perdu. Au risque d’être long, je vais essayer de formuler ce que j’ai compris car je me dis que ça peut être utile. 

J’ai l’impression que ma confusion vient de l’usage de « _place_ » qui a l’air de changer au cours de l’analyse. C’est un point important car, de prime abord, la notion de « _place_ » ne parait pas trop compliquée au lecteur mais il me semble que ce n’est pas si évident surtout dès que l’on fait les réductions (projections) à partir de ces _places_.  

Si j’ai bien compris : une _place_ est un groupe d’_elements_ (étudiants) relié à un groupe de _sets_ (universités). L’idée de créer une _place_ est donc d’éviter la redondance entre des relations dyadiques _element-set_ (étudiant-université) et de regrouper ensemble tous les étudiants qui ont strictement le même profil d’affiliation (en suivant la notion d’équivalence structurale). De fait, si je comprends bien, l’information essentielle qui définit une _place_ particulière se trouve dans la colonne `PlaceDetail` de l'objet `Result1$PlacesData` renvoyé par la fonction (il me semble que ça serait bien d’insister là-dessus car le nom de la colonne peut donner l’impression que c’est une simple précision). 

Ce qui, pour moi, n’est pas évident à comprendre : c’est que par la suite les étudiants sont bien rassemblés en groupes selon l’équivalence structurale (les fameuses _places_) mais les universités restent, quant à elles, individualisées.
Si c’est effectivement cela : alors, dans ce qui suit, on obtient deux réseaux très différents grâce à une double-opération de _reduction_ (mathématiquement une projection) qui n'est pas strictement symétrique :

- Un réseau d’_elements /places_ (groupes d’étudiants comme sommets) reliés entre eux par le nombre de _sets_ en commun (nb universités comme liens valuées). 
- Un réseau de _sets_ (chaque sommet représente une université) reliés entre eux par différentes _places_ (groupes d’étudiants ayant les mêmes affiliations).

Si on pose les choses comme ceci, je trouve que l’interprétation ne va pas de soi, en particulier pour le réseau des universités (_sets_) qui m’apparait difficile à interpréter.  Car on pourrait imaginer un cas théorique où deux universités sont reliées par une seule place mais qui comprend 1000 étudiants : elles seraient alors reliées par un lien de poids 1 (mais qui "cacheraient" mille étudiants) et deux autres universités pourraient être reliées par un lien de poids 5 (avec 5 places ne comportant qu’un élement/étudiant - chacune). Ainsi le poids des liens entre universités ne renvoie pas directement à une quantité d’étudiants en commun (comme dans une projection classique) mais à une plus ou moins grandes diversités des profils d’affiliation des étudiants qui sont (entre autres) allés à ces deux universités (_ça fait mal à la tête_ : ) ).
Si, comme je le crois, l’interprétation du réseau des _sets_ (universités) n’est pas évidente : il est possible de le dire et de supprimer certaines analyses qui concernent cette projection. Sinon, une ou deux phrases supplémentaires pour décrire l’intérêt de l’analyse du réseau des _sets_ (universités) me sembleraient utiles.

Si j'ai mal compris ces points de la méthode et la signification des projections, peut-être faut-il faire des petites précisions pour éviter cela. 

### Suggestions 

[l41](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L41C1-L41C19) : le chargement de l’ensemble du `tidyverse` est, selon moi, superflu. De mon côté j’ai pu faire tourner tout le code avec seulement `readr` et `dplyr`. 

[l42 et 44](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L42C1-L44C20) : pourquoi charger directement `Places` et `kableExtra` alors qu’ils ont un appel dédié dans des _chunks_ plus bas. 

[l63](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L63C1-L65C4) : la figure est superbe ! très lisible et compréhensible. Je me demande juste : étant donné qu'il n'y a pas de comparaison avec la méthode classique de la double projection, est-il utile de garder les blocs B1 et B2 ?

[l123](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L123C1-L123C11) : je ne suis pas sûr que la commande `names()` apporte quelque chose ici. Selon moi, pas besoin de décrire cette fonction, ni même `summary`. En revanche, cela peut être l’occasion de faire un commentaire général sur la source/ les données elles-mêmes (sur la répartition des nationalités par exemple).

[l131- 134](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L131C2-L135C78). Il y a peut-être moyen de clarifier les étapes (et employer le mot de « _reduction_ » comme dans le premier schéma pour ne pas avoir de confusion avec la projection classique – même s’il s’agit bien d’une forme de projection)
1.	_Extracting places from the two-mode network_
2.	_Reduction: creating a network of places & a network of sets_
3.	_Applying one-mode network metrics on places and sets_ 
4.	_Communities of places and sets_
5.	_From structural equivalence to regular equivalence: the k-places function_ 

[l177](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L177C1-L177C140) : il me semble qu’ici il y a quelque chose de déterminant => on passe bien de 682 liens dyadiques (étudiant-université) à 223 _places_. Cette réduction peut sembler importante mais effectivement en mettant en regard le nombre d’étudiants et d’universités (les deux types de sommets), ce n’est pas tant que ça. Il me semble qu’un commentaire thématique pourrait être ajouté : soit directement ici,  soit au moment des histogrammes (notamment l214 car le fait que 80% des places caractérisent un seul étudiant chaque fois peut ouvrir des questions sur la structure du réseau et sur l'utilisation de la méthode des places).

[l219](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L219C1-L219C56) : pas sûr que l’histogramme soit nécessaire ici. La table me semble suffire. Sinon changement le nom des axes et changer la gradation de l’axe x (seulement les entiers de 1 à 4).

[l246](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L246C1-L247C1) : je trouve ce type d'interprétation thématique super ! Si l’interprétation en elle-même n’est pas reproductible, en revanche je me demande comment les pourcentages ont été calculés. Y-a-t-il un moyen de les retrouver à partir du tableau des _places_ ? ou de la table des liens ? (si oui, il me semble que mettre le _chunk_ de code pour ce calcul serait très utile.

[l301-347](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L301C1-L301C19) : peut-être revoir les titres pour être plus explicite (cf. commentaire sur les lignes 131-134). Il me semble qu’il faut dire clairement au lecteur ou à la lectrice que l’on va faire une double projection (appelé « _reduction_ » dans le premier graphique) mais à partir des _places_ et des _sets_. 

[l307-320](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L307C1-L320C4) : Je trouve ça très heuristique de faire la projection manuellement à partir des matrices mais dans ce cas là un petit commentaire (#) au-dessus de chaque étape serait utile dans ce premier _chunk_ (et cela éviterait d'ailleurs de faire plusieurs _chunks_ séparés par des phrases). Autre possibilité au niveau du code : on considère que la projection ne fait pas du tout partie de l’article et on peut utiliser la méthode interne à `igraph` (dans un seul _chunk_) : 
```r
# deuxième manière de faire la projection 
# réseau à partir de la liste de liens de Places
Net <- graph_from_data_frame(Result1$Edgelist, directed = FALSE)
## transformation en 2-mode 
V(Net)$type <- bipartite_mapping(Net)$type
# projection
projNet <- bipartite_projection(Net, multiplicity = TRUE)
Net1 <- projNet$proj1  # réseau des elements/places
Net2 <- projNet$proj2 # réseau des sets (universités)
```
 
[l351](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L351C1-L357C4) : ajouter ou tester un algorithme de spatialisation serait utile pour améliorer la lisibilité  : 
      `layout = layout_components`
Je verrais bien un petit commentaire par exemple la signification des sommets isolés : si j’ai bien suivi il s’agit des groupes d’étudiants (places) qui n’ont été affiliés qu’à une seule université. On devrait y trouver par exemple la place P145(18-1) , c’est-à-dire le groupe de 18 étudiants qui ont été à Harvard et seulement à Harvard. 
Sur les graphiques de réseaux en général, deux pistes d'amélioration : 
1. Supprimer toutes les informations superflues (vue le nombre de sommets, les labels me semblent superflus)
2. Représenter certaines variables qui aident à la compréhension des entités manipulées : par exemple le nombre d'étudiants dans chaque _place_ serait une plus-value pour bien rappeler que la _place_ est  une  _classe collective d'équivalence_ et pas une personne. 

[371-377](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L371C1-L377C34) : Ces précisions/détails ne me paraissent pas utiles, surtout dans le corps du texte. Peut-être mettre ces éléments dans le premier _chunk_ sous la forme de commentaire (# ) de chaque paramètre de la fonction plot de `igraph`.

[l389-397](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L389C1-L397C57) : cette section pourrait éventuellement être allégée. Ma proposition : ne pas lister toutes ces métriques globales et n’en choisir qu’une ou deux qui permettant de faire une interprétation thématique sur les données.   

[l441](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L441C1-L441C11) : je ne suis pas sûr de suivre le commentaire sur la paire d’universités _Columbia-New York University_ : il me semble que l’on voit que ces deux universités sont reliées par 4 places (c’est-à-dire par _4 ensembles d’étudiants aux profils universitaires distincts mais qui ont été au moins dans ces deux universités_). L’interprétation proposée ici me semble plutôt relever d’une projection « classique » où les universités seraient liées par le nombre d’étudiants en commun. 

[l443-450 ](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L443C1-L450C30): peut-être qu'il est souhaitable de diminuer le nombre de métriques présentées/calculées dans cette section. 
Pour quelqu’un d’extérieur aux données et à la thématique, je trouve l’interprétation difficile : exemple avec le degré (non pondéré), il s’agit d’un nombre de relations avec les autres universités, une relation correspondant ici au fait d’avoir au moins une place en commun (possiblement seulement un seul étudiant ayant suivi un cursus dans les deux universités).

[l493](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L493) : peut-être développer un peu car je ne comprends pas trop l’idée d’hétérogénéité dans le commentaire. 

[l507 ](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L507C21-L507C21)– 532 : peut-être ne pas séparer _find_ et _plot_ dans deux sous-parties distinctes

[l543-550](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L543C1-L550C4) : pour ce graphique (et le suivant avec les universités) : est-ce nécessaire de faire figurer les liens ?  (si oui, mettre de la transparence, et peut-être inutile de différencier entre rouges et noirs car trop peu lisible). Pas sur que les labels soient nécessaires.  Dans tous les cas, peut-être essayer un autre algorithme de spatialisation que celui par défaut. 

[l575](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L575C1-L575C23) et [639](https://github.com/rzine-reviews/place-rzine/blob/3f5642c2f44e9781a4763094c24dd2601092c27d/index.Rmd#L638) : les parties 3.3 et 3.4 pourraient être regroupées en une seule et réduites. On suppose que le lecteur/ la lectrice sait utiliser `igraph` et R (ou ira chercher l’information ailleurs) donc l’affichage des tableaux avec l’appartenance aux communautés ne me parait pas essentiel. 
On pourrait par exemple s’en tenir à la représentation et au commentaire thématique d’un ou deux sous-graphes (Princeton et/ou Columbia).

**Comment by carmand03** [comment]
Merci à Paul Gourdon pour sa relecture attentive et ses suggestions très pertinentes. Je me suis efforcée de les suivre au plus près. Ci-joint mes réponses point par point. 

[Armand_rzine_replies.pdf](https://github.com/user-attachments/files/16618632/Armand_rzine_replies.pdf)

**Comment by pgourdongeo** [comment]
Merci beaucoup Cécile pour cette nouvelle version, je trouve l'ensemble très clair, intéressant et prêt pour la publication. 


Sur le code tout tourne bien  => mais j'ai eu les mêmes warnings que le camarade Laurent Beauguitte. Aussi, pour la relative durabilité du code, cela pourrait être utile de remplacer les fonctions anciennes  de igraph ( "deprecated" ) par leur version actuelle (souvent un simple remplacement du "." par le underscore "_")


### Quelques dernières petites suggestions pour le texte :

[85](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L85)   :  "this package is the only available library that enables place detection and analysis" ici ma proposition est complètement optionnelle mais, vu le thème de l'article, on pourrait envisager pointant vers les packages et approches qui permettent d'aborder la structural equivalence sous R. J'avais notamment mis deux liens en ce sens : 
https://rstudio-pubs-static.s3.amazonaws.com/436072_01fce54f3c25458381fee52ec65396fc.html#structural_equivalence_methods
https://search.r-project.org/CRAN/refmans/netdiffuseR/html/struct_equiv.html


[97](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L97)  : peut-être remplacer la tournure un peu prescriptive ("it is recommended to export the edge lists") par quelque chose comme "it may be useful to" car sortir de R pour la visualisation peut aussi s'avérer très chronophage.

[272](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L272)  : il me semble qu'il manque un verbe ici après "were" : " This suggests that many students were relatively during". 

Tout de suite après il y a cette phrase => "Fewer students (25) attended more than two universities during their studies. More specifically, 21 students attended 3 and 4 students attended 4 different universities." : dans le graphique il s'agit de places et non pas de students. Donc, si je le comprends bien, cela montre qu'il y a 25 places qui ont plus de deux universités (mais en tout cas le calcul ne permet pas de savoir que ces 25 places correspondent chacune à un étudiant unique)

[276](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L276)  ici c'est vraiment du détail mais la définition des "significant places" n'est pas  très explicite. Je veux dire on pourrait très bien faire une étude qui s'intéresse aux parcours atypiques (et les places intéressantes seraient par exemple celles avec un seul étudiant) ou au contraire les places les plus courantes (et dans ce cas on sélectionnerait les places avec plus de 7 ou 10 étudiants). Possible donc d'allonger la phrase en disant qu'on écarte les places qui renvoient à des parcours et curricula uniques 

[393](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L393C208-L393C231) pb typographie car les "$" mettent le texte en italique. Sans doute faut-il mettre les objets R entre `` comme avant les ":"  pour éviter ceci  => `Result1$Edgelist$Places`

[522](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L522) :  pour éviter l'ambiguité, ce sont bien 226 places qui sont liées par 1606 "sets of universities"  ,mettre seulement "universities" pourrait être trompeur (il n'y a que 146 universités différentes dans le jeu de données, comme le montre la phrase suivante sur l'autre projection )


 [550](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L550C125-L550C199) :    "pairs of places (academic trajectories) which share 2 sets (universities)" => deux petites remarques :  

- Une sur lexique :  je trouve ça super de donner une interprétation sémantique aux places dans cette étude empirique => "1 place = 1 academic trajectory" mais dans ce cas vérifier que c'est bien ce terme qui est mis partout dans le texte (il me semble qu'à certain moment les places sont décrites comme des curricula). 

 

- Deuxième remarque, pour éviter les ambiguïtés :  "2 sets (i.e 2 two different combinations of universities) " plutôt que de mettre seulement "universities" entre parenthèse.

 [843](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L843)  : je crois que c'est 146 universités (et non pas 145)

 [879](https://github.com/rzine-reviews/place-rzine/blob/5d9fbb9c78a3c7f8ec1e385a0b81b8f5f62d965c/index.Rmd#L879) :  comment trouve-t-on les différences entre les parcours de F. Sec Fong et Edward Y.K. Kwong à partir du tableau affiché ?  

Merci encore pour ce texte très utile !

**Comment by carmand03** [comment]
Merci Paul pour ta relecture attentive et tes conseils avisés !
